# Generated by Django 2.2.17 on 2025-02-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="capital",
            field=models.CharField(default=" ", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="country",
            name="top_level_domains",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
    ]
